name: CI Build Wheel
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CIBW_ARCHS_LINUX: auto # aarch64
      CIBW_ARCHS_MACOS: x86_64 universal2
      CIBW_ARCHS_WINDOWS: auto
      CIBW_ENVIRONMENT_LINUX: 'PATH="$PATH:/usr/share/rust/.cargo/bin:$HOME/.cargo/bin"'
      CIBW_ENVIRONMENT_MACOS: 'PATH="$PATH:/usr/share/rust/.cargo/bin:$HOME/.cargo/bin"'
      CIBW_ENVIRONMENT_WINDOWS: 'RUSTFLAGS="-Ctarget-feature=+crt-static"'
      CIBW_BUILD: "cp39-*"
      CIBW_SKIP: "cp39-musl*"
      CIBW_BEFORE_ALL_LINUX: >
        yum install -y libffi-devel openssl-devel &&
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.63.0 --profile=minimal -y &&
        rustup show &&
        cargo install empty-library || true
      CIBW_BUILD_VERBOSITY: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust
        if: runner.os != 'Linux'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63.0
          profile: minimal

      - name: Install Rust aarch64-apple-darwin target
        if: runner.os == 'macOS'
        run: rustup target add aarch64-apple-darwin

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: 3.9

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl